### PR TITLE
Redirect link scripts

### PR DESCRIPTION
**Pull request by jakirkham**
* Re-renders with `conda-smithy` version `1.2.0`. Please see PR ~~( https://github.com/conda-forge/vega-feedstock/pull/9 )~~ ( https://github.com/conda-forge/vega-feedstock/pull/11 ).
* Pulls in PR ( https://github.com/conda-forge/vega-feedstock/pull/1 ).
* Redirects to `.messages.txt` to aid in debugging bad installs.

### CODE REVIEW

**Comment by jakirkham** [comment]
Can clean up a bit after PR ( https://github.com/conda-forge/vega-feedstock/pull/9 ) is merged.

**Comment by jakevdp** [comment]
We should merge #9 before this, yes?

**Comment by jakirkham** [comment]
That would keep things cleaner. 😄

**Comment by jakirkham** [comment]
Cleaned up and is now passing.

**Comment by jakevdp** [comment]
Looks good, thanks

**Pull request merged**
