### PR TITLE
bump to version 0.4.3

### PR DESCRIPTION
**Pull request by jakevdp**

### CODE REVIEW

**Comment by jakirkham** [comment]
Please [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` version `1.3.2` before merging this or any other PR. Can do in this PR or in a separate one that is merged first.

**Comment by jakevdp** [comment]
I'm getting an error with conda-smithy 1.3.2:

```
jakesmac:vega-feedstock jakevdp$ conda smithy rerender
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
No anaconda token. Create a token via
  anaconda auth --create --name conda-smithy --scopes "repos conda api"
and put it in ~/.conda-smithy/anaconda.token
Fetching package metadata .......
Traceback (most recent call last):
  File "/Users/jakevdp/anaconda/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/Users/jakevdp/anaconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 239, in main
    args.subcommand_func(args)
  File "/Users/jakevdp/anaconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 185, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/Users/jakevdp/anaconda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 444, in main
    render_run_docker_build(env, config, forge_dir)
  File "/Users/jakevdp/anaconda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 44, in render_run_docker_build
    if not ResolvedDistribution(meta, pkgs).skip():
  File "/Users/jakevdp/anaconda/lib/python3.5/site-packages/conda_build_all/resolved_distribution.py", line 77, in __getattr__
    with setup_vn_mtx_case(self.special_versions):
  File "/Users/jakevdp/anaconda/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Users/jakevdp/anaconda/lib/python3.5/site-packages/conda_build_all/resolved_distribution.py", line 21, in setup_vn_mtx_case
    orig_npy = conda_build.config.config.CONDA_NPY
AttributeError: module 'conda_build.config' has no attribute 'config'
```

**Comment by jakevdp** [comment]
OK, looks like I had an old version of conda-build-all (0.11). Perhaps that requirement should be added to the conda-smithy recipe?

**Comment by jakevdp** [comment]
Rerender in #13. I'll rebase this PR once that is merged.

**Comment by jakirkham** [comment]
Sorry I missed that. Glad you got it sorted though.

The situation is more that to use `conda-build` version `2.0.x` one needs `conda-build-all` version `1.0.0` and the `conda-smithy` version `1.2.0` or greater. Basically, this error wouldn't have occurred with `conda-build` version `1.21.x` and the old `conda-build-all`. Not sure the right way to specify that ATM as I don't think we have conditional versioning of this sort.

**Comment by jakevdp** [comment]
Appveyor is failing because when activating the environment, ``The input line is too long.``

Seems related to [this issue](https://github.com/conda/conda/issues/1923), and the fix there is basically "make your ``PATH`` variable shorter".

It seems fixing this would require modifying the AppVeyor scripts somehow... any ideas on that?

**Comment by jakevdp** [comment]
@pelson @ocefpaf would love to hear any solutions for this Appveyor failure...

Also, Travis has been Queued for nearly 24 hours now.

**Comment by ocefpaf** [comment]
> @pelson @ocefpaf would love to hear any solutions for this Appveyor failure...

Sorry @jakevdp but I have no idea on both cases. `Travis-CI` had its outages before, but never like this.

Maybe we can work around the AppVeyor error... @msarahan do you have any idea why this is affecting only PY27? I lost track of things but it seems like the feedstoscks are still downloading `miniconda`. I thought we changed that a long time ago to use the AppVeyor's pre-installed miniconda. Maybe that will help here. If I get some extra time I will take a look this weekend.

**Comment by jakirkham** [comment]
IIUC there was some bad interaction between `conda` and AppVeyor. @msarahan made a new deployment of `conda` to fix this last night, but I guess it took some time to propagate through. Most builds that have been restarted since appear to be working.

**Comment by jakevdp** [comment]
Appveyor still failing on 2.7, due to the PATH being too long.

**Comment by jakevdp** [comment]
Looks like some difference in how paths are specified between ``http://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86.exe`` and ``http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe``

**Comment by jakevdp** [comment]
FYI, AppVeyor has miniconda built-in, so maybe conda-forge should be using their version? https://github.com/appveyor/ci/issues/359

**Comment by ocefpaf** [comment]
> FYI, AppVeyor has miniconda built-in, so maybe conda-forge should be using their version? appveyor/ci#359

Like I said above

> thought we changed that a long time ago to use the AppVeyor's pre-installed miniconda. 

I do use it in my non-conda-forge builds and I do remember @jjhelmus implementing that here. But since `conda-build-setup` was introduced I lost track as things got buried into deep layers and harder to debug :unamused:

**Comment by jakirkham** [comment]
> FYI, AppVeyor has miniconda built-in, so maybe conda-forge should be using their version? https://github.com/appveyor/ci/issues/359

We changed to AppVeyor's included Miniconda in [staged-recipes]( https://github.com/conda-forge/staged-recipes/pull/982 ). It was kind of a [mess]( https://github.com/conda-forge/staged-recipes/pull/982#issuecomment-231244796 ) as it is [pretty out-of-date in some cases]( https://github.com/conda-forge/staged-recipes/pull/982#issuecomment-231245054 ). It was suggested that we do the [same in feedstocks]( https://github.com/conda-forge/conda-smithy/issues/176 ). However, the person suggesting it changed their mind due to some [issues they encountered]( https://github.com/conda-forge/conda-smithy/issues/176#issuecomment-231369417 ). So we skipped it.

Given using Miniconda is already a problem as we spend a couple of minutes just updating from defaults packages to conda-forge packages and sometimes (more [frequently of late]( https://github.com/Anaconda-Platform/support/issues/78 )) run into connectivity issues by slamming Anaconda.org in this way, the general feeling is we should have our own [installer]( https://github.com/conda-forge/staged-recipes/issues/610#issuecomment-227273497 ) to cutdown build time and limit this impact. The situation with using an outdated copy of Miniconda will undoubtedly be no different in this respect.

We packaged [everything]( https://github.com/conda-forge/staged-recipes/issues/1063 ) needed to do this. Someone even got the basics for an installer together during a Hackathon at SciPy. It was transferred to a [repo]( http://github.com/conda-forge/conda-forge-anvil ) here. Though there are a number of [important issues]( https://github.com/conda-forge/conda-forge-anvil/issues ) we need to address before we can proceed. Help on any of these would be appreciated.

**Comment by ocefpaf** [comment]
It is a pity you think that is messy, or worse, have our own installer. That kind "forkish" behavior is the one that drivers people away.

BTW the default AppVeyor miniconda works wonders in all my other projects. Including building with `conda-build 2`. All I do is `conda update --all` without the `conda-forge` channel of course since conda/conda-build from there is unreliable, and I get all latest versions of `conda` and `conda-build` ready to go.

Ping @asmeurer who is also puzzled with some the the weird decision in conda-forge in https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/38

**Comment by jakevdp** [comment]
Is there any significant difference in what you get if you (a) download and install miniconda-latest or (b) use an old miniconda and run ``conda update conda``?

**Comment by ocefpaf** [comment]
> It was kind of a mess

BTW this is what I use and I do not think it is messy:

```yaml
environment:
  matrix:
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
```

> as it is pretty out-of-date in some cases.

That part is easily fixed by a `conda update --all`.

**Comment by ocefpaf** [comment]
> Is there any significant difference in what you get if you (a) download and install miniconda-latest or (b) use an old miniconda and run ``conda update conda``?

Not to my knowledge. My Other auto-build conda packages projects work just fine that way.

**Comment by asmeurer** [comment]
I had heard that Miniconda was going to change to install conda into a separate environment, but I just tested the latest Miniconda OS X installer and it didn't do that, so I'm not so sure.

**Comment by jakevdp** [comment]
Can someone restart the AppVeyor build here?

**Comment by ocefpaf** [comment]
Just did. Btw you should have AppVeyor rights here to restart it too. Let me know if that is not working.

**Comment by jakirkham** [comment]
The failure will be resolved by [re-rendering]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` version `1.3.3`.

**Comment by jakevdp** [comment]
Appveyor builds completed after 10 hours in the queue, but one hit a network error. Since there's [no way for Appveyor to restart a single job](https://github.com/appveyor/ci/issues/58) I restarted them all. Sigh...

**Comment by jakirkham** [comment]
> but one hit a network error.

You're not alone. Hence the long queue. 😒

Trying to track this down with upstream. ( https://github.com/Anaconda-Platform/support/issues/78 )

> Since there's no way for Appveyor to restart a single job I restarted them all. 

Asked upstream for this feature. ( https://github.com/appveyor/ci/issues/1114 )

**Comment by jakevdp** [comment]
Another single network error in Appveyor after half a day in the queue. I'll restart **all the builds** again. This is seriously trying my patience...

**Comment by jakevdp** [comment]
Given the constraint these two trials put on the probability of failure and duration of the queue, I could model it as a multinomial process compute an expectation value for how long this will take to finish... but it would probably just depress me.

Or maybe I should just merge?

**Comment by ocefpaf** [comment]
@jakevdp just merge it as you can restart it on master to get the missing package to be uploaded. You already know that the build will pass and that error is only network issue.

Unfortunately an `OS X` image update on Travis-CI scared some people and they issued hundreds of feedstocks updates that are not skipping CIs and, in most cases, are not even affected by the `OS X` iamge update :unamused:

**Comment by jakevdp** [comment]
OK!

**Comment by jakirkham** [comment]
FWIW it seems the merge passed on the first try.

**Comment by jakevdp** [comment]
> FWIW it seems the merge passed on the first try.

yep, I noticed that :smile:

**Pull request merged**
