### PR TITLE
squelch link script output

### PR DESCRIPTION
**Pull request by bollwyvl**
Nobody likes the output from the post-link scripts from `jupyter nbextension enable`. This redirects any such output.

I'll be doing these for the other extensions as well :)

### CODE REVIEW

**Comment by jakevdp** [comment]
What's problematic about the output?

**Comment by jakirkham** [comment]
Agreed. I kind of like seeing this output as it tells me the post linking worked. Also, it is pretty short; so, don't really find it a hindrance for following log output. Why should it be removed here or elsewhere?

**Comment by bollwyvl** [comment]
Folks:
Whoops, meant to raise this issue here, first:
https://github.com/conda-forge/conda-forge.github.io/issues/173

**Comment by pelson** [comment]
To revive this, I think what you are proposing is fine, though it will be necessary to rebase and bump to build number 2.

**Comment by jakevdp** [comment]
I think this is addressed by #4.

**Comment by jakirkham** [comment]
Oops, missed this one when I opened that PR. So these are two halves of the problem. This suppresses the output of the commands and the other suppresses the commands from being printed to the console. So we still need this too. Sorry about the confusion.

**Comment by pelson** [comment]
@bollwyvl - we could do with a rebase on this PR if you wouldn't mind. Otherwise, we can hit merge! :+1:

**Comment by jakirkham** [comment]
...and a build number bump (believe it should be 3 now).

**Pull request merged**
