### PR TITLE
bump to version 0.4.2

### PR DESCRIPTION
**Pull request by jakevdp**

### CODE REVIEW

**Comment by jakevdp** [comment]
So... travis is failing because Python 2.7 apparently uses ``yield from`` in its own site-packages:
```
Compiling /Users/travis/miniconda3/envs/_build/lib/python2.7/site-packages/pexpect/async.py ...
  File "/Users/travis/miniconda3/envs/_build/lib/python2.7/site-packages/pexpect/async.py", line 16
    transport, pw = yield from asyncio.get_event_loop()\
                             ^
SyntaxError: invalid syntax
```
That can't be good...

**Comment by jakevdp** [comment]
Looks like it's from the ``pexpect`` package, in the ``pexpect/async.py`` module. Looking at the code, it's designed so that the file should never be imported in the normal use of the package (imports are conditional on ``asyncio`` existing, which is a python 3-only module). But it appears some part of the conda build process is automatically compiling all ``.py`` files in the package, and in the course of that runs into a syntax error on ``yield from``.

@jakirkam – any ideas here?

**Comment by jakevdp** [comment]
Note this is also caught in the conda-build process for ``pexpect``, but for some reason the error is ignored there: https://travis-ci.org/conda-forge/pexpect-feedstock/jobs/148997040#L516

**Comment by ocefpaf** [comment]
Jake rerendering the feedstock might fix this b/c it will update
conda-build.

I'll send more info later. Only online on the phone today.

**Comment by jakevdp** [comment]
Thanks @ocefpaf – I'm not sure how to re-render the feedstock. I found [conda-render](http://conda.pydata.org/docs/commands/build/conda-render.html), but running it on the recipe here doesn't change anything.

**Comment by jakevdp** [comment]
(googling "conda re-render feedstock" mostly turns-up conda-forge commit messages)

**Comment by ocefpaf** [comment]
You need to install `conda-smithy` and then type `conda smithy rerender` from the recipe root directory.
Sorry, I was on  my cell when I sent that message and I got lazy :stuck_out_tongue_winking_eye:

**Comment by jakevdp** [comment]
Thanks!

**Comment by ocefpaf** [comment]
BTW some background on the issue: old versions of `conda-build` failed when byte-compiling Python 3 code while in Python 2 env. That broke builds instead of just skipping a feature that would not be available on Python 2.

Up until recently we were patching packages to remove the Python 3 code in that situation but, since https://github.com/conda/conda-build/pull/1146 , we can leave the code untouched.

`vega` was not at fault here but `vega-feedstock` was still using an old `conda-build` and the re-rendering should fix that.

**Comment by jakevdp** [comment]
We're seeing the same error after the re-render. Any thoughts?

**Comment by jakirkham** [comment]
There should have been some changes to `.travis.yml` that were not included in the last commit. Try re-rendering again and make sure everything gets committed.

**Comment by jakevdp** [comment]
Ah, thanks! Should have done ``git add . -u`` rather than ``git add * -u``.

**Comment by jakirkham** [comment]
No worries. Happens to me sometimes too. Particularly when I add a new file like a patch. 😒

**Comment by jakevdp** [comment]
Looks like things are fixed. Once the travis build finishes, I'll merge. Thanks for the help, @ocefpaf & @jakirkham!

**Pull request merged**
