### PR TITLE
Update to version 0.4.1

### PR DESCRIPTION
**Pull request by jakevdp**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@jakevdp send PRs from a fork instead of the main repo. That will trigger the CIs twice and the package will be uploaded before the merge. (Which sometimes if not desired as we may be uploading something that is broken that only a human review would show.)

**Comment by jakevdp** [comment]
Will do, sorry.

**Comment by jakevdp** [comment]
Appveyor is failing on Python 3.X with x86. For some reason after conda installing ipython, it's unable to import IPython. Any ideas?

**Comment by ocefpaf** [comment]
> Appveyor is failing on Python 3.X with x86. For some reason after conda installing ipython, it's unable to import IPython. Any ideas?

Not sure. It may be a `conda-build` bug. Ping @msarahan.

**Comment by msarahan** [comment]
I don't think it's a conda-build bug, (un)fortunately.  Having things spread across Python 3.x like this, and not localized to one of the more troublesome platforms (Py3.4 in particular) exonerates conda-build somewhat.  Have you tried building this locally?  It seems like it might be something like a module name issue - did anything change with the IPython module with Python 3.x?

You can activate the _test environment after a failed build to help debug what things should be.  If you don't have a Windows system available, I recommend using AppVeyor's RDP feature: https://www.appveyor.com/docs/how-to/rdp-to-build-worker

I'm guessing the simple import of IPython won't work right away, but with RDP, you should be able to figure out what's going wrong.

If it's a conda-build bug, then it is probably something to do with incorrect values in os.environ["PATH"], sys.path - check to make sure that the _test environment appears properly.  If it is not a conda-build bug, then it might be that your IPython packages don't have content you expect (look in _test/lib/site-packages/IPython...)  Try to check any relevant ```__init__.py``` modules for why that name doesn't exist.  Is it a case sensitivity issue?  I don't know why Py2.7 would work, but others not in this case.

**Comment by ocefpaf** [comment]
> You can activate the ```_test``` environment after a failed build to help debug what things should be.  If you don't have a Windows system available, I recommend using AppVeyor's RDP feature: https://www.appveyor.com/docs/how-to/rdp-to-build-worker

Did not know abou this. Very useful!

**Comment by jakevdp** [comment]
> Have you tried building this locally? 

I don't have access to any Windows machine. But the build process is basically ``python setup.py install`` followed by ``jupyter nbextension install``; nothing too complicated.

Also, this worked a month ago, so I'm confused as to why it would fail now.

**Comment by jakevdp** [comment]
TBH, I'm more interested in making this available ASAP to OSX/Linux users than to trouble-shoot for Windows users. Do you think it's OK to merge?

**Comment by ocefpaf** [comment]
> Do you think it's OK to merge?

Yep. That kind of decision in cases like this is up to the maintainers of the recipe. In that case you :wink: 

I only recommend to open an issue so we can keep track of the problem.

**Comment by jakevdp** [comment]
Actually, I just realized that since I pushed to a conda-forge branch these builds are already available :)

**Comment by jakevdp** [comment]
Just so I don't mess things up further, I'm going to close this PR and re-open from a personal branch with the build number updated.

**Comment by msarahan** [comment]
> I don't have access to any Windows machine. But the build process is basically python setup.py install followed by jupyter nbextension install; nothing too complicated.

Check out the appveyor link I posted.  It is a really nice service that they offer.  You add a bit to appveyor.yml temporarily, and it lets you connect via remote desktop into the build worker.  You have up to an hour to mess around.  With this, you don't really even need a local windows machine to develop or debug recipes any more, though having to reconnect every hour might be tedious for very involved development or debugging.

I don't think it's anything in your build that is wrong.  Rather, I think it is one of your dependencies (most likely ipython) that isn't quite what you expect.

> Also, this worked a month ago, so I'm confused as to why it would fail now.

There are a lot of dependencies.  Some of these might be new conda-forge packages replacing what was defaults for your last build.  Defaults is also in flux, with many recipes being converted from a legacy format to conda recipes and being made public at https://github.com/continuumIO/anaconda-recipes.  Sadly, I don't think it's a safe assumption that just because something used to work, it still will today.

**Pull request closed without merging**
